### ISSUE TITLE
CTRL + NumpadKey

### ISSUE THREAD

**Issue by FilipLaurentiu** [jaywcjlove/react-hotkeys#10]
This is not working. 
   hotkeys('ctrl+1', (x) => {
      console.log('test');
    });

Also, neither this:
    hotkeys('ctrl+shift+1', (x) => {
      console.log('test');
    });

**Comment by jaywcjlove** [comment]
@FilipLaurentiu I updated the official website example and it looks fine. Provide a running platform?

E.g. `Chrome 70`
