### ISSUE TITLE
Holding modifier only reads as 1 event

### ISSUE THREAD

**Issue by chandlervdw** [jaywcjlove/react-hotkeys#12]
As it stands, a feature like copy + paste feels cumbersome, as you are required to release all keys before typing another combination. Most people will hold their finger on the modifier key while hitting `c`, then `v`. This only results in one event, at least when I use `keyName="*"` (using a specific list also doesn't work). 

Am I missing something or is this just a limitation of the library?

**Comment by jaywcjlove** [comment]
Can you give an example?

E.g: https://codepen.io/jaywcjlove/pen/BbEeVX

**Comment by chandlervdw** [comment]
This is not in the `hotkeys-js` lib, but in the `react-hot-keys` npm module. In that repo's readme, it says it's a fork of `hotkeys-js`. 

I couldn't figure out how to properly import `react-hot-keys` into codepen (I used `https://unpkg.com/react-hot-keys@1.3.0/umd/react-hot-keys.min.js`). It kept complaining about 
```
Cannot read property 'Component' of undefined
```
where `undefined` was `react` within `react-hot-keys`.

I'm not sure what to say other than your `hotkeys-js` implementation in the codepen worked but it does not work when using the `<Hotkeys />` component.

**Comment by jaywcjlove** [comment]
@chandlervdw https://codepen.io/jaywcjlove/pen/bJxbwG

**Comment by chandlervdw** [comment]
This is perfect, as it proves my point. Hold down shift and press a, then press s. You only get the keyup and keydown events for pressing a. It should register both a and s events.

**Comment by chandlervdw** [comment]
Thanks, I'm unsure of what I had going that was breaking that functionality.
