### ISSUE TITLE
Possible values of keyName

### ISSUE THREAD

**Issue by jklingen92** [jaywcjlove/react-hotkeys#13]
Could you please include in the README all possible recognized values of `keyName` or a link to where we could find them. I'm trying to recognize arrow keys and I'm not sure how to tell that to the component.

**Comment by jklingen92** [comment]
I found it here: https://github.com/jaywcjlove/hotkeys/blob/master/src/var.js

**Comment by jaywcjlove** [comment]
@jklingen92 You can test this by: https://codepen.io/jaywcjlove/pen/yrRmYE
