### ISSUE TITLE
Include support for the splitKey option

### ISSUE THREAD

**Issue by leroydev** [jaywcjlove/react-hotkeys#26]
I want to be able to bind to the shortcut `CTRL and +`.
To be able to do this, I need support for the `splitKey` option (https://github.com/jaywcjlove/hotkeys/pull/105).

I think it'd be ideal if it could be used like this:
```tsx
<Hotkeys keyName="ctrl_+" splitKey="_">...</Hotkeys>
```

I will try and make a pull request with this feature. :)

**Comment by jaywcjlove** [comment]
@leroydev 👍
