### ISSUE TITLE
onKeyDown will trigger once even if HotKey unmount

### ISSUE THREAD

**Issue by Frezc** [jaywcjlove/react-hotkeys#3]
reproduce https://codesandbox.io/s/5v32pv9v3p
1. press enter
2. click switch and unfocus button, HotKey will unmount
2. press 'enter', the onKeyDown will trigger

**Comment by Frezc** [comment]
另外在项目里面用的时候就算unmount了onKeyDown还是会一直触发，在上面的code里没法重现。onKeyUp表现正常

**Comment by jaywcjlove** [comment]
@Frezc 我测试一下

**Comment by jaywcjlove** [comment]
@Frezc 更新 `react-hot-keys@1.0.11` 新版本
