### ISSUE TITLE
Depending on hotkeys-js in both dependencies and peerDependencies

### ISSUE THREAD

**Issue by mvasilkov** [jaywcjlove/react-hotkeys#31]
Hi,

The dependency on hotkeys-js is specified twice:
https://github.com/jaywcjlove/react-hotkeys/blob/5fed73c624a41b101dee2bbf5609fd1362e67378/package.json#L64-L82

In some scenarios this leads to the following warning when installing:
```
warning " > react-hot-keys@2.5.0" has unmet peer dependency "hotkeys-js@>=3.7.3".
```

Great work on the library BTW!

**Comment by jaywcjlove** [comment]
@mvasilkov Upgrade `+ react-hot-keys@2.5.1`
