### ISSUE TITLE
add/remove Event listener on Children

### ISSUE THREAD

**Issue by Attrash-Islam** [jaywcjlove/react-hotkeys#5]
Hi,
I loved the idea. How about to support binding the add/remove the event listeners on the root ref of the childrens?

That way, when a group of inputs below `<ReactHotKeys />` can be separated from another group with another `<ReactHotKeys />`, currently the Component is binding to the same global `document`

Thanks :rose:

**Comment by Attrash-Islam** [comment]
Yes, I saw that. But how that related to the event isolation?

I suggested instead of binding on document to bind the event on the root ref wrapped by the component.

I can supply more examples tomorrow if needed

**Comment by jaywcjlove** [comment]
```js
hotkeys('o, enter', {
  scope: 'wcj',
  element: document.getElementById('warpper'),
}, function(){ 
  console.log('do something else');
});
```

The new version of [hotkeys](https://github.com/jaywcjlove/hotkeys) has been supported. `react-hotkeys` needs improvement.
