### ISSUE TITLE
"delete" is not support

### ISSUE THREAD

**Issue by AntoninSorrento** [jaywcjlove/react-hotkeys#8]
delete is not support

![image](https://user-images.githubusercontent.com/26902024/45806310-4d9cda00-bcf3-11e8-90ce-a257f433e9b3.png)

**Comment by jaywcjlove** [comment]
@AntoninSorrento This is a compatibility issue. use `backspace`  to achieve..

```jsx
<Hotkeys 
  keyName="backspace" 
  onKeyDown={this.onKeyDown.bind(this)}
  onKeyUp={this.onKeyUp.bind(this)}
>
  test
</Hotkeys>
```
